spring:
    application:
        name: springboot-security-example
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: pwd123
        url: jdbc:mysql://localhost:3306/tokoroti
        username: fajar
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20

    flyway:
        enabled: true
        locations: classpath:db/migration
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true
        show-sql: true
logging:
    level:
        web: DEBUG
        org.springframework.security: DEBUG
server:
    port: 8080
